# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf2039909757a643af05f332ea7a78d5d2b503e5c6bc12a619925e1178c0aa0ba4f8ef71ad290f0a294538b0b9dd2a8756576304b4a9388171582b9981f6f7e2

test:
  secret_key_base: 90b91d1c3219a26fc1d570f616a0e5a55b7b7f0861beeff50a443ed50e82b4ac09a75bffc5b1158b6adbbc5820b1964f9d37448f7465d3cf9ce332a5dd6da451

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
